---
# Remove unwanted pre-installed packages from EndeavourOS

- name: Remove Firefox (replaced with Vivaldi)
  become: yes
  pacman:
    name:
      - firefox
    state: absent
  ignore_errors: yes  # Don't fail if Firefox isn't installed

- name: Clean package cache
  become: yes
  command: pacman -Sc --noconfirm
  changed_when: false
