---
# Remove unwanted pre-installed packages from EndeavourOS

- name: Remove Firefox (replaced with Vivaldi)
  become: yes
  pacman:
    name: "{{ bloat_packages }}"
    state: absent
  ignore_errors: yes # Don't fail if packages aren't installed in the first place

- name: Clean package cache
  become: yes
  command: pacman -Sc --noconfirm
  changed_when: false
