---
# Developer role variables

# Development tools and languages
dev_packages:
  - podman
  - podman-compose
  - podman-docker
  - ripgrep
  - fd
  - fzf
  - lazygit

# VSCode extensions to install
vscode_extensions:
  - ms-vscode.cpptools
  - ms-python.python
  - rust-lang.rust-analyzer
  - golang.go
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - dbaeumer.vscode-eslint
