---
# Install Firefox browser

- name: Install Firefox via snap
  community.general.snap:
    name: firefox
    state: present
  become: yes

# Note: Firefox config is typically managed through Firefox Sync
# If you want to manage profiles/extensions via Ansible, add tasks here
