[general]
live_config_reload = true

[font]
normal = { family = "Monaspace Neon NF", style = "Regular" }
bold = { family = "Monaspace Neon NF", style = "Bold" }
italic = { family = "Monaspace Xenon NF", style = "Italic" }
bold_italic = { family = "Monaspace Xenon NF", style = "Bold Italic" }

# Key bindings
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017" # send ctrl+w for word deletion

[terminal]
shell = "fish"

[[hints.enabled]]
binding = { key = "F1" }
regex = "\\S{8,}" # non-whitespace groups
post_processing = true
action = "Copy"
mouse = { enabled = true }

[[hints.enabled]]
binding = { key = "F2" }
regex = "\\S{8,}" # non-whitespace groups
post_processing = true
command = "xdg-open"
hyperlinks = true
mouse = { enabled = true }

