---
# Install Steam and configure

- name: Install Steam
  become: yes
  pacman:
    name:
      - steam
    state: present

- name: Create Steam config directory
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.steam"
    state: directory
    mode: '0755'

- name: Display Steam installation complete
  debug:
    msg: "Steam installed. Launch Steam to complete initial setup and enable Proton in Settings > Steam Play."
